name: borsar
channels:
- defaults
dependencies:
- python>=3.8
- pip
- mkl>=2021.4.0
- numpy=1.20.1
- scipy
- matplotlib
- pandas
- xlrd
- scikit-learn
- scikit-image
- h5py
# dev/testing libraries:
- statsmodels>=0.13.2
- pytest
- pytest-cov
- psutil
- numpydoc
- flake8
# likely not needed:
- joblib
- pip:
  - mne
  - h5io
  - pydocstyle
  - codespell
  - sphinx_gallery
  - sphinx_bootstrap_theme
